app:
    resource: @AppBundle/Controller/
    type:     annotation

app_alumno:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /

app_backend:
    pattern: /backend
    defaults: { _controller: AppBundle:Default:backend }

inicio:
    pattern: /
    defaults: { _controller: FrameworkBundle:Redirect:redirect,route: general_main, permanent: true }
general_main:
    path:     /Inicio
    defaults: { _controller: AppBundle:Default:index }
convocatorias:
    pattern:  /Convocatorias/
    defaults: { _controller: AppBundle:Default:convocatorias }
contacto:
    pattern:  /Contacto/
    defaults: { _controller: AppBundle:Default:contacto }
criteriospnp:
    pattern:  /CriteriosPNP/
    defaults: { _controller: AppBundle:Default:criteriospnp }
estudiantes:
    pattern:  /Estudiantes/
    defaults: { _controller: AppBundle:Default:estudiantes }
investigadores:
    pattern:  /Docentes/
    defaults: { _controller: AppBundle:Default:docentes }
lineasii:
    pattern:  /LineasII/
    defaults: { _controller: AppBundle:Default:lineasII }
lineasme:
    pattern:  /LineasME/
    defaults: { _controller: AppBundle:Default:lineasME }
programaii:
    pattern:  /ProgramaII/
    defaults: { _controller: AppBundle:Default:programaII }
programame:
    pattern:  /ProgramaME/
    defaults: { _controller: AppBundle:Default:programaME }
publicaciones:
    pattern:  /Publicaciones/
    defaults: { _controller: AppBundle:Default:publicaciones }
usuario_new:
    pattern:  /backend/usuarioNuevo
    defaults: { _controller: AppBundle:Default:new }
login:
    pattern:  /backend/login
    defaults: { _controller: AppBundle:Default:login }
login_check:
    pattern:  /backend/login_check
logout:
    pattern:  /backend/logout