alumno:
    path:     /
    defaults: { _controller: "AppBundle:Alumno:index" }

alumno_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Alumno:show" }

alumno_new:
    path:     /new
    defaults: { _controller: "AppBundle:Alumno:new" }

alumno_create:
    path:     /create
    defaults: { _controller: "AppBundle:Alumno:create" }
    methods:  POST

alumno_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Alumno:edit" }

alumno_update:
    path:     /{id}/update
    defaults: { _controller: "AppBundle:Alumno:update" }
    methods:  [POST, PUT]

alumno_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Alumno:delete" }
    methods:  [POST, DELETE]
