app_docente:
    resource: "@AppBundle/Resources/config/routing/docente.yml"
    prefix:   /backend/docente

app_alumno:
    resource: "@AppBundle/Resources/config/routing/alumno.yml"
    prefix:   /backend/alumno



